name: Syntax Tester

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt
    - name: Checks
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics